# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UI/edit_entity.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditEntityForm(object):
    def setupUi(self, EditEntityForm):
        EditEntityForm.setObjectName("EditEntityForm")
        EditEntityForm.resize(450, 480)
        self.gridLayout = QtWidgets.QGridLayout(EditEntityForm)
        self.gridLayout.setObjectName("gridLayout")
        self.txt_account_number = QtWidgets.QLineEdit(EditEntityForm)
        self.txt_account_number.setObjectName("txt_account_number")
        self.gridLayout.addWidget(self.txt_account_number, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(EditEntityForm)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(EditEntityForm)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        self.txt_entity_name = QtWidgets.QLineEdit(EditEntityForm)
        self.txt_entity_name.setObjectName("txt_entity_name")
        self.gridLayout.addWidget(self.txt_entity_name, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(EditEntityForm)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.combo_bank = QtWidgets.QComboBox(EditEntityForm)
        self.combo_bank.setObjectName("combo_bank")
        self.gridLayout.addWidget(self.combo_bank, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(EditEntityForm)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.txt_account_details = QtWidgets.QLineEdit(EditEntityForm)
        self.txt_account_details.setObjectName("txt_account_details")
        self.gridLayout.addWidget(self.txt_account_details, 3, 1, 1, 1)
        self.btn_save_entity = QtWidgets.QPushButton(EditEntityForm)
        self.btn_save_entity.setObjectName("btn_save_entity")
        self.gridLayout.addWidget(self.btn_save_entity, 4, 1, 1, 1)

        self.retranslateUi(EditEntityForm)
        QtCore.QMetaObject.connectSlotsByName(EditEntityForm)

    def retranslateUi(self, EditEntityForm):
        _translate = QtCore.QCoreApplication.translate
        EditEntityForm.setWindowTitle(_translate("EditEntityForm", "Edit Entity"))
        self.label_2.setText(_translate("EditEntityForm", "Bank Name:"))
        self.label.setText(_translate("EditEntityForm", "Entity Name:"))
        self.label_4.setText(_translate("EditEntityForm", "Account Description"))
        self.label_3.setText(_translate("EditEntityForm", "Account Number:"))
        self.btn_save_entity.setText(_translate("EditEntityForm", "Save"))
