# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UI/exports.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Exports(object):
    def setupUi(self, Exports):
        Exports.setObjectName("Exports")
        Exports.resize(640, 477)
        self.gridLayout = QtWidgets.QGridLayout(Exports)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.table_export_files = QtWidgets.QTableWidget(Exports)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_export_files.sizePolicy().hasHeightForWidth())
        self.table_export_files.setSizePolicy(sizePolicy)
        self.table_export_files.setMaximumSize(QtCore.QSize(300, 16777215))
        self.table_export_files.setBaseSize(QtCore.QSize(300, 0))
        self.table_export_files.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_export_files.setObjectName("table_export_files")
        self.table_export_files.setColumnCount(0)
        self.table_export_files.setRowCount(0)
        self.horizontalLayout.addWidget(self.table_export_files)
        self.table_file_transactions = QtWidgets.QTableWidget(Exports)
        self.table_file_transactions.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_file_transactions.setObjectName("table_file_transactions")
        self.table_file_transactions.setColumnCount(0)
        self.table_file_transactions.setRowCount(0)
        self.horizontalLayout.addWidget(self.table_file_transactions)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.txt_search = QtWidgets.QLineEdit(Exports)
        self.txt_search.setObjectName("txt_search")
        self.horizontalLayout_2.addWidget(self.txt_search)
        self.btn_search = QtWidgets.QPushButton(Exports)
        self.btn_search.setObjectName("btn_search")
        self.horizontalLayout_2.addWidget(self.btn_search)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btn_export_selected = QtWidgets.QPushButton(Exports)
        self.btn_export_selected.setObjectName("btn_export_selected")
        self.horizontalLayout_2.addWidget(self.btn_export_selected)
        self.btn_export_all = QtWidgets.QPushButton(Exports)
        self.btn_export_all.setObjectName("btn_export_all")
        self.horizontalLayout_2.addWidget(self.btn_export_all)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.table_transactions = QtWidgets.QTableWidget(Exports)
        self.table_transactions.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_transactions.setObjectName("table_transactions")
        self.table_transactions.setColumnCount(0)
        self.table_transactions.setRowCount(0)
        self.gridLayout.addWidget(self.table_transactions, 1, 0, 1, 1)

        self.retranslateUi(Exports)
        QtCore.QMetaObject.connectSlotsByName(Exports)

    def retranslateUi(self, Exports):
        _translate = QtCore.QCoreApplication.translate
        Exports.setWindowTitle(_translate("Exports", "Form"))
        self.btn_search.setText(_translate("Exports", "Search"))
        self.btn_export_selected.setText(_translate("Exports", "Export Selected"))
        self.btn_export_all.setText(_translate("Exports", "Export All"))
        self.table_transactions.setSortingEnabled(True)
