# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UI/main_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main_App(object):
    def setupUi(self, Main_App):
        Main_App.setObjectName("Main_App")
        Main_App.resize(640, 480)
        self.verticalLayout = QtWidgets.QVBoxLayout(Main_App)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tab_Widget = QtWidgets.QTabWidget(Main_App)
        self.tab_Widget.setObjectName("tab_Widget")
        self.tab_Entity = QtWidgets.QWidget()
        self.tab_Entity.setObjectName("tab_Entity")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_Entity)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.layout_edit_entity = QtWidgets.QVBoxLayout()
        self.layout_edit_entity.setObjectName("layout_edit_entity")
        self.horizontalLayout_2.addLayout(self.layout_edit_entity)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.tab_Widget.addTab(self.tab_Entity, "")
        self.tab_Imports = QtWidgets.QWidget()
        self.tab_Imports.setObjectName("tab_Imports")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_Imports)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.layout_imports = QtWidgets.QVBoxLayout()
        self.layout_imports.setObjectName("layout_imports")
        self.verticalLayout_4.addLayout(self.layout_imports)
        self.tab_Widget.addTab(self.tab_Imports, "")
        self.tab_Suppliers = QtWidgets.QWidget()
        self.tab_Suppliers.setObjectName("tab_Suppliers")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_Suppliers)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.layout_suppliers = QtWidgets.QVBoxLayout()
        self.layout_suppliers.setObjectName("layout_suppliers")
        self.horizontalLayout.addLayout(self.layout_suppliers)
        self.tab_Widget.addTab(self.tab_Suppliers, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.layouts_exports = QtWidgets.QVBoxLayout()
        self.layouts_exports.setObjectName("layouts_exports")
        self.gridLayout.addLayout(self.layouts_exports, 0, 0, 1, 1)
        self.tab_Widget.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.tab_Widget)

        self.retranslateUi(Main_App)
        self.tab_Widget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Main_App)

    def retranslateUi(self, Main_App):
        _translate = QtCore.QCoreApplication.translate
        Main_App.setWindowTitle(_translate("Main_App", "Bank File Generator"))
        self.tab_Widget.setTabText(self.tab_Widget.indexOf(self.tab_Entity), _translate("Main_App", "Entity"))
        self.tab_Widget.setTabText(self.tab_Widget.indexOf(self.tab_Imports), _translate("Main_App", "Imports"))
        self.tab_Widget.setTabText(self.tab_Widget.indexOf(self.tab_Suppliers), _translate("Main_App", "Suppliers"))
        self.tab_Widget.setTabText(self.tab_Widget.indexOf(self.tab), _translate("Main_App", "Exports"))
