# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UI/select_entity.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelectEntityForm(object):
    def setupUi(self, SelectEntityForm):
        SelectEntityForm.setObjectName("SelectEntityForm")
        SelectEntityForm.resize(309, 480)
        self.verticalLayout = QtWidgets.QVBoxLayout(SelectEntityForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(SelectEntityForm)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.btn_add_entity = QtWidgets.QPushButton(SelectEntityForm)
        self.btn_add_entity.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_add_entity.setBaseSize(QtCore.QSize(0, 0))
        self.btn_add_entity.setObjectName("btn_add_entity")
        self.horizontalLayout.addWidget(self.btn_add_entity)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.list_entities = QtWidgets.QListWidget(SelectEntityForm)
        self.list_entities.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.list_entities.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.list_entities.setObjectName("list_entities")
        self.verticalLayout.addWidget(self.list_entities)
        self.btn_load_entity = QtWidgets.QPushButton(SelectEntityForm)
        self.btn_load_entity.setObjectName("btn_load_entity")
        self.verticalLayout.addWidget(self.btn_load_entity)

        self.retranslateUi(SelectEntityForm)
        QtCore.QMetaObject.connectSlotsByName(SelectEntityForm)

    def retranslateUi(self, SelectEntityForm):
        _translate = QtCore.QCoreApplication.translate
        SelectEntityForm.setWindowTitle(_translate("SelectEntityForm", "Select Entity"))
        self.label.setText(_translate("SelectEntityForm", "Select Entity"))
        self.btn_add_entity.setText(_translate("SelectEntityForm", "Add New"))
        self.btn_load_entity.setText(_translate("SelectEntityForm", "Load"))
