# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UI/suppliers.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Suppliers(object):
    def setupUi(self, Suppliers):
        Suppliers.setObjectName("Suppliers")
        Suppliers.resize(640, 480)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Suppliers)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tbl_suppliers = QtWidgets.QTableWidget(Suppliers)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbl_suppliers.sizePolicy().hasHeightForWidth())
        self.tbl_suppliers.setSizePolicy(sizePolicy)
        self.tbl_suppliers.setMinimumSize(QtCore.QSize(700, 0))
        self.tbl_suppliers.setMaximumSize(QtCore.QSize(1200, 400))
        self.tbl_suppliers.setBaseSize(QtCore.QSize(1000, 0))
        self.tbl_suppliers.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.tbl_suppliers.setProperty("showDropIndicator", False)
        self.tbl_suppliers.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbl_suppliers.setObjectName("tbl_suppliers")
        self.tbl_suppliers.setColumnCount(0)
        self.tbl_suppliers.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.tbl_suppliers)
        self.layout_graphs = QtWidgets.QHBoxLayout()
        self.layout_graphs.setObjectName("layout_graphs")
        self.horizontalLayout_2.addLayout(self.layout_graphs)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.line = QtWidgets.QFrame(Suppliers)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.txt_tran_search = QtWidgets.QLineEdit(Suppliers)
        self.txt_tran_search.setObjectName("txt_tran_search")
        self.horizontalLayout_3.addWidget(self.txt_tran_search)
        self.btn_tran_search = QtWidgets.QPushButton(Suppliers)
        self.btn_tran_search.setObjectName("btn_tran_search")
        self.horizontalLayout_3.addWidget(self.btn_tran_search)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.btn_status_change = QtWidgets.QPushButton(Suppliers)
        self.btn_status_change.setObjectName("btn_status_change")
        self.horizontalLayout_3.addWidget(self.btn_status_change)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tbl_transactions = QtWidgets.QTableWidget(Suppliers)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbl_transactions.sizePolicy().hasHeightForWidth())
        self.tbl_transactions.setSizePolicy(sizePolicy)
        self.tbl_transactions.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tbl_transactions.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbl_transactions.setProperty("showDropIndicator", False)
        self.tbl_transactions.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbl_transactions.setObjectName("tbl_transactions")
        self.tbl_transactions.setColumnCount(0)
        self.tbl_transactions.setRowCount(0)
        self.verticalLayout.addWidget(self.tbl_transactions)
        self.verticalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(Suppliers)
        QtCore.QMetaObject.connectSlotsByName(Suppliers)

    def retranslateUi(self, Suppliers):
        _translate = QtCore.QCoreApplication.translate
        Suppliers.setWindowTitle(_translate("Suppliers", "Suppliers"))
        self.tbl_suppliers.setSortingEnabled(True)
        self.btn_tran_search.setText(_translate("Suppliers", "Search"))
        self.btn_status_change.setText(_translate("Suppliers", "Change Status"))
        self.tbl_transactions.setSortingEnabled(True)
